// Auto-generated by scripts/quick-pack.py.
// Provides the qq_magic_napi_register symbol that Linux QQ does not export
// itself, so NapCat's native addons can register without an "undefined
// symbol" dlopen failure.  napi_module_register is resolved from the host
// process at runtime, which avoids a build-time dependency on <node_api.h>.
#include <dlfcn.h>

extern "C" void qq_magic_napi_register(void *m) {
    typedef void (*reg_fn)(void *);
    static reg_fn fn = (reg_fn) dlsym(RTLD_DEFAULT, "napi_module_register");
    if (fn) {
        fn(m);
    }
}
